version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: temurchlen
    ports:
      - 5634:5634

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080